### ISSUE TITLE
Holes?

### ISSUE THREAD

**Issue by ljharb** [tc39/Array.prototype.includes#31] opened 2015-05-24 02:43 UTC
What happens with a sparse array? Should `Array(1).includes()` be `true` (indicating that holes are traversed) or `false` (indicating that holes are skipped)?

All of the Array.prototype methods in ES6/ES2015 skip holes, so I'd expect `includes` to do so as well for consistency.

**Comment by domenic** [comment] 2015-05-24 02:49
Dupe of #15.

**Closed by domenic** 2015-05-24 02:49 UTC

**Comment by ljharb** [comment] 2015-05-24 02:50
A ha, thank you for confirming
